In [181]:
import pandas as pd
chosenpaths_links = pd.read_csv(r'J:\Projects\FasTrips\tableau\path-set\fake_join_chosenpaths_links.csv')
chosenpaths_paths = pd.read_csv(r'J:\Projects\FasTrips\tableau\path-set\fake_join_chosenpaths_paths.csv')
pathset_links = pd.read_csv(r'J:\Projects\FasTrips\tableau\path-set\pathset_links.csv')
pathset_paths = pd.read_csv(r'J:\Projects\FasTrips\tableau\path-set\pathset_paths.csv')

In [182]:
import numpy as np

In [183]:
### 
# See if the observed chosenpath is the pathset_paths at all
df = chosenpaths_paths[chosenpaths_paths['record_type'] == 'observed']

In [184]:
# Set of descriptions from observed records
# Get all the unique person IDs

In [228]:
df.groupby('iteration').count()

,person_id,trip_list_id_num,pathdir,pathmode,pf_iteration,pathnum,pf_cost,pf_probability,description,chosen,missed_xfer,sim_cost,logsum_component,logsum,probability,record_type
iteration,,,,,,,,,,,,,,,,
1,103,103,103,103,103,103,103,103,103,103,103,103,103,103,103,103
2,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108

In [203]:
def check_path_existence(row, pathset_df, unique_id, lookup_field):
    """
    Compare field contents from chosen paths vs entire path set,
    Return 1 if chosen path exists in pathset, 0 otherwise
    """
    
    if len(pathset_paths[(pathset_df[unique_id] == row[unique_id]) & \
                        (pathset_df[lookup_field] == row[lookup_field])]) > 0:
        return 1
    else:
        return 0

In [204]:
df.apply(check_path_existence, pathset_df=pathset_paths, unique_id='person_id', lookup_field='description', axis=1)

211    1
212    1
213    1
214    1
215    1
216    1
217    1
218    1
219    1
220    1
221    1
222    1
223    1
224    1
225    1
...
407    1
408    1
409    1
410    1
411    1
412    1
413    1
414    1
415    1
416    1
417    1
418    1
419    1
420    1
421    1
Length: 211, dtype: int64

In [188]:
# Also, return the probability
# pathset_paths[(pathset_paths['person_id'] == test_person) & ((pathset_paths['person_id'] == test_description))

In [222]:
def get_path_attribute(row, pathset_df, unique_id, lookup_field, value_field):
    """
    For a chosen path, return parameter from path set.
    E.g., return path probability (value_field) for observed path, based on matching path description (lookup_field)
    """
    
    if len(pathset_paths[(pathset_df[unique_id] == row[unique_id]) & \
                        (pathset_df[lookup_field] == row[lookup_field])]) > 0:
        try:
            return pathset_paths[(pathset_df[unique_id] == row[unique_id]) &  \
                             (pathset_df[lookup_field] == row[lookup_field])][value_field].values[0]
        except:
            return 0
    else:
        return 0

In [223]:
# Probability for the chosen path
prob = pd.DataFrame(df.apply(get_path_attribute, pathset_df=pathset_paths, unique_id='person_id',
                             lookup_field='description', value_field='pf_probability', axis=1))
prob.columns = ['probability_of_actual']

In [224]:
prob

     probability_of_actual
211               0.031882
212               0.328170
213               0.029454
214               0.336549
215               0.014465
216               0.133469
217               0.490573
218               0.154610
219               0.489014
220               0.094540
221               0.427088
222               0.333195
223               0.305485
224               0.146109
225               0.067694
226               0.997448
227               0.006614
228               0.140161
229               0.203535
230               0.006775
231               0.328378
232               0.058618
233               0.263492
234               0.140181
235               0.026793
236               0.498998
237               0.330635
238               0.169435
239               0.016087
240               0.162037
..                     ...
392               0.331692
393               0.047153
394               0.244581
395               0.122070
396               0.048209
397               0.007158
398               0.911601
399               0.496609
400               0.005235
401               0.341174
402               0.005795
403               0.560094
404               0.259036
405               0.279725
406               0.066068
407               0.017837
408               0.439873
409               0.331828
410               0.332579
411               0.004475
412               0.992844
413               0.279186
414               0.045262
415               0.111058
416               0.001515
417               0.424088
418               0.196576
419               0.476990
420               0.700990
421               0.253107

[211 rows x 1 columns]

In [177]:
# % Of routes over 20%
prob['threshold'] = prob['probability_of_actual'].apply(lambda x: 1 if x >= 0.2 else 0)

In [178]:
prob['threshold'].mean()

0.46445497630331756

In [179]:
pathset_paths[(pathset_paths['person_id'] == test_person) & (pathset_paths['description'] == test_description)]

,person_id,trip_list_id_num,pathdir,pathmode,pf_iteration,pathnum,pf_cost,pf_probability,description,chosen,missed_xfer,sim_cost,logsum_component,logsum,probability,iteration,simulation iteration
11,1095531_3,1,2,transit,1,11,14.244888,0.031882,152 walk_access 23715 local_bus MUN19I_22086 2...,1,0,18.548129,8.803390e-09,0.000001,0.007347,1,4
2127,1095531_3,1,2,transit,1,11,14.244888,0.031882,152 walk_access 23715 local_bus MUN19I_22086 2...,1,0,18.548129,8.803390e-09,0.000001,0.007347,2,2

In [180]:
# To be done in Tableau
prob[['probability_of_actual','threshold']]

     probability_of_actual  threshold
211               0.031882          0
212               0.328170          1
213               0.029454          0
214               0.336549          1
215               0.014465          0
216               0.133469          0
217               0.490573          1
218               0.154610          0
219               0.489014          1
220               0.094540          0
221               0.427088          1
222               0.333195          1
223               0.305485          1
224               0.146109          0
225               0.067694          0
226               0.997448          1
227               0.006614          0
228               0.140161          0
229               0.203535          1
230               0.006775          0
231               0.328378          1
232               0.058618          0
233               0.263492          1
234               0.140181          0
235               0.026793          0
236               0.498998          1
237               0.330635          1
238               0.169435          0
239               0.016087          0
240               0.162037          0
..                     ...        ...
392               0.331692          1
393               0.047153          0
394               0.244581          1
395               0.122070          0
396               0.048209          0
397               0.007158          0
398               0.911601          1
399               0.496609          1
400               0.005235          0
401               0.341174          1
402               0.005795          0
403               0.560094          1
404               0.259036          1
405               0.279725          1
406               0.066068          0
407               0.017837          0
408               0.439873          1
409               0.331828          1
410               0.332579          1
411               0.004475          0
412               0.992844          1
413               0.279186          1
414               0.045262          0
415               0.111058          0
416               0.001515          0
417               0.000000          0
418               0.000000          0
419               0.000000          0
420               0.000000          0
421               0.000000          0

[211 rows x 2 columns]

In [166]:
chosenpaths_paths

,person_id,trip_list_id_num,pathdir,pathmode,pf_iteration,pathnum,pf_cost,pf_probability,description,chosen,missed_xfer,sim_cost,logsum_component,logsum,probability,iteration,record_type
0,1095531_3,1,2,transit,1,11,14.244888,0.031882,152 walk_access 23715 local_bus MUN29I_22086 2...,1.00,0,18.548129,8.800000e-09,1.200000e-06,7.347466e-03,1,model
1,1140514_1,2,2,transit,1,0,41.861609,0.328170,578 walk_access 13405 light_rail MUNHO_18412 2...,1.00,0,45.090190,2.620000e-20,1.310000e-19,1.990383e-01,1,model
2,1141305_1,3,2,transit,1,2,66.148808,0.029454,948 walk_access 30730 premium_bus 81_GG24NBA_7...,1.00,0,68.807451,1.310000e-30,1.770000e-28,7.420215e-03,1,model
3,1143233_3,4,2,transit,1,1,32.952124,0.336549,271 walk_access 27862 local_bus MUN5I_19840 27...,1.00,0,37.034342,8.240000e-17,4.050000e-16,2.034726e-01,1,model
4,1338147_1,5,1,transit,1,1,41.484442,0.014465,701 walk_access 25179 local_bus MUN19O_22152 2...,1.01,0,50.793488,8.720000e-23,2.470000e-20,3.529139e-03,1,model
5,1338147_1,6,2,transit,1,1,23.384560,0.133469,569 walk_access 23878 local_bus MUN19I_22091 2...,1.00,0,30.672341,4.780000e-14,6.910000e-12,6.912311e-03,1,model
6,1362557_3,7,1,transit,1,0,10.461028,0.490573,726 walk_access 24510 local_bus MUN12O_21218 2...,1.00,0,14.099197,7.530000e-07,3.460000e-06,2.174570e-01,1,model
7,1362557_3,8,2,transit,1,2,22.089497,0.154610,630 walk_access 23889 express_bus MUN8XI_20419...,1.00,0,28.765330,3.220000e-13,2.280000e-11,1.411263e-02,1,model
8,1362557_4,9,1,transit,1,0,10.461028,0.489014,726 walk_access 24510 local_bus MUN12O_21218 2...,1.00,0,14.099197,7.530000e-07,3.470000e-06,2.172233e-01,1,model
9,1362557_4,10,2,transit,1,6,22.580831,0.094540,630 walk_access 23897 express_bus MUN8XI_20419...,1.00,0,28.273760,5.260000e-13,2.290000e-11,2.297668e-02,1,model
10,1365175_1,11,2,transit,1,0,44.503590,0.427088,246 walk_access 26031 local_bus MUN24I_22911 2...,1.00,0,56.800837,2.150000e-25,4.150000e-25,5.172814e-01,1,model
11,1377028_1,12,2,transit,1,2,34.908442,0.333195,640 walk_access 23834 express_bus MUN8XI_20403...,1.00,0,52.651613,1.360000e-23,5.640000e-19,2.410000e-05,1,model
12,1379781_1,13,2,transit,1,1,38.266493,0.305485,773 walk_access 13402 light_rail MUNJO_17744 2...,1.00,0,40.446130,2.720000e-18,2.060000e-17,1.316957e-01,1,model
13,1379781_2,14,2,transit,1,1,34.874612,0.146109,773 walk_access 13401 light_rail MUNJO_17744 2...,1.00,0,36.349082,1.640000e-16,1.700000e-15,9.639778e-02,1,model
14,1383839_2,16,2,transit,1,1,42.126303,0.067694,791 walk_access 13402 light_rail MUNKO_17970 2...,1.00,0,47.533218,2.270000e-21,2.630000e-18,8.638710e-04,1,model
15,1388787_1,17,2,transit,1,0,99.491893,0.997448,1193 walk_access 7674 local_bus 28_121_8455 76...,1.00,0,110.170840,1.420000e-48,1.420000e-48,9.999612e-01,1,model
16,1462712_1,18,1,transit,1,11,23.302441,0.006614,808 walk_access 30728 local_bus MUN38LO_25545 ...,1.00,0,25.157671,1.190000e-11,8.010000e-09,1.481156e-03,1,model
17,1462712_1,19,1,transit,1,2,24.008072,0.140161,748 walk_access 24901 local_bus MUN30I_23747 2...,1.00,0,34.579024,9.610000e-16,3.220000e-13,2.979419e-03,1,model
18,1485392_1,21,2,transit,1,0,37.846458,0.203535,621 walk_access 13404 light_rail MUNLO_18256 2...,1.00,0,40.481095,2.630000e-18,2.820000e-17,9.295707e-02,1,model
19,1490741_2,22,2,transit,1,15,69.042373,0.006775,773 walk_access 24673 premium_bus 80_GG4NB_763...,1.00,0,71.756400,6.860000e-32,5.090000e-29,1.348232e-03,1,model
20,1501312_1,23,2,transit,1,1,37.099820,0.328378,649 walk_access 54006 light_rail MUNKO_17986 5...,1.00,0,41.297791,1.160000e-18,8.090000e-18,1.435139e-01,1,model
21,1504746_3,24,1,transit,1,8,35.253441,0.058618,286 walk_access 24311 local_bus MUN14SHORTO_21...,1.00,0,39.108918,1.040000e-17,1.150000e-15,8.982089e-03,1,model
22,1508142_2,25,1,transit,1,1,31.262691,0.263492,171 walk_access 23964 local_bus MUN9O_20827 20...,1.00,0,38.196907,2.580000e-17,9.280000e-17,2.778041e-01,1,model
23,1527884_2,26,1,transit,1,0,33.673800,0.140181,92 walk_access 20770 express_bus MUN8XI_20370 ...,1.00,0,40.365457,2.950000e-18,7.820000e-17,3.767686e-02,1,model
24,1527884_2,27,2,transit,1,1,46.188353,0.026793,790 walk_access 13402 light_rail MUNLO_18305 1...,1.00,0,47.701324,1.920000e-21,1.200000e-19,1.598772e-02,1,model
25,1635458_1,28,1,transit,1,1,47.497895,0.498998,199 walk_access 13407 light_rail MUNKI_17797 5...,1.00,0,51.676699,3.610000e-23,1.420000e-22,2.540015e-01,1,model
26,1636733_1,29,2,transit,1,2,21.555907,0.330635,789 walk_access 24720 local_bus MUN30O_23903 2...,1.00,0,24.376269,2.590000e-11,2.760000e-10,9.380046e-02,1,model
27,1679352_2,31,2,transit,1,2,43.570141,0.169435,743 walk_access 52732 local_bus 30_292S_8201 2...,1.00,0,45.717596,1.400000e-20,2.640000e-19,5.281335e-02,1,model
28,1680336_1,32,2,transit,1,17,20.918715,0.016087,944 walk_access 24701 local_bus MUN1O_19254 26...,1.00,0,23.217011,8.260000e-11,1.530000e-08,5.394888e-03,1,model
29,1680696_1,33,2,transit,1,5,45.508833,0.162037,934 walk_access 13402 light_rail MUNNI_18630 5...,1.00,0,51.686804,3.570000e-23,1.690000e-21,2.116012e-02,1,model
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,7016454_1,90,1,transit,1,0,39.951858,0.331692,553 walk_access 26282 light_rail MUNNI_18611 1...,1.00,0,45.348162,2.020000e-20,1.390000e-19,1.453967e-01,2,observed
393,7016618_4,91,1,transit,1,8,16.976527,0.047153,658 walk_access 27230 local_bus MUN38_33RDO_25...,1.00,0,20.982913,7.710000e-10,7.340000e-08,1.050207e-02,2,observed
394,7016618_4,92,2,transit,1,0,19.006162,0.244581,309 walk_access 27284 local_bus MUN44O_26267 2...,1.00,0,23.759626,4.800000e-11,3.570000e-10,1.343335e-01,2,observed
395,7016828_2,93,2,transit,1,3,27.906007,0.122070,635 walk_access 27483 local_bus MUN38_33RDI_25...,1.00,0,31.373801,2.370000e-14,1.360000e-12,1.745176e-02,2,observed
396,7017091_3,94,1,transit,1,3,48.704720,0.048209,625 walk_access 27840 local_bus MUN38FTMI_2493...,1.01,0,55.604855,7.100000e-25,1.950000e-24,3.643832e-01,2,observed
397,7017091_3,95,2,transit,1,4,50.069816,0.007158,822 walk_access 30710 local_bus MUN30SHORTI_23...,1.01,0,55.326715,9.370000e-25,2.520000e-23,3.726519e-02,2,observed
398,7017091_4,96,1,transit,1,0,51.871107,0.911601,625 walk_access 27545 local_bus MUN29O_23592 2...,1.00,0,55.037882,1.250000e-24,1.250000e-24,9.986401e-01,2,observed
399,7017091_4,97,2,transit,1,0,48.662947,0.496609,20 walk_access 22605 local_bus MUN29I_23523 27...,1.00,0,55.970734,4.920000e-25,2.110000e-24,2.336291e-01,2,observed
400,7017104_3,98,1,transit,1,26,33.811344,0.005235,271 walk_access 27903 local_bus MUN31I_24213 2...,1.00,0,42.654014,2.990000e-19,3.540000e-16,8.456410e-04,2,observed
401,7017104_3,99,2,transit,1,1,33.578332,0.341174,335 walk_access 26824 local_bus MUN24O_22996 2...,1.00,0,36.932569,9.130000e-17,1.280000e-16,7.120662e-01,2,observed
402,7017673_3,100,1,transit,1,8,43.571981,0.005795,612 walk_access 27505 local_bus MUN38_33RDI_25...,1.01,0,49.665168,2.700000e-22,1.020000e-19,2.642808e-03,2,observed
403,7017673_3,101,1,transit,1,0,36.510663,0.560094,844 walk_access 26702 local_bus MUN19O_22160 2...,1.00,0,41.841775,6.740000e-19,1.500000e-18,4.483907e-01,2,observed
404,7018763_1,102,1,transit,1,1,56.831120,0.259036,823 walk_access 25478 express_bus MUN8XO_20527...,1.00,0,61.670291,1.650000e-27,2.750000e-26,6.000268e-02,2,observed
405,7018763_1,103,2,transit,1,0,77.675398,0.279725,310 walk_access 26625 local_bus MUN2I_19505 25...,1.00,0,87.595483,9.070000e-39,3.240000e-38,2.801397e-01,2,observed
406,7018891_1,104,1,transit,1,1,48.344513,0.066068,361 walk_access 24820 express_bus MUN82XI_2874...,1.00,0,50.688090,9.690000e-23,3.910000e-21,2.481972e-02,2,observed
407,7018891_1,105,1,transit,1,6,36.415069,0.017837,829 walk_access 54035 light_rail MUNFO_17306 2...,1.00,0,39.607207,6.290000e-18,1.080000e-15,5.812575e-03,2,observed
408,7018891_1,106,2,transit,1,0,21.778613,0.439873,286 walk_access 24429 local_bus MUN19I_22087 2...,1.00,0,30.544376,5.430000e-14,3.530000e-13,1.538235e-01,2,observed
409,7159381_1,107,1,transit,1,2,53.688245,0.331828,536 walk_access 54007 light_rail MUNKO_17937 5...,1.00,0,63.663964,2.240000e-28,4.280000e-27,5.245761e-02,2,observed
410,7159381_1,108,2,transit,1,2,62.807331,0.332579,927 walk_access 54005 light_rail MUNKI_17828 5...,1.00,0,78.645550,6.990000e-35,1.330000e-33,5.245761e-02,2,observed
411,7162015_1,109,1,transit,1,2,101.030049,0.004475,690 walk_access 24645 local_bus MUN38LO_25488 ...,1.01,0,114.396195,2.080000e-50,3.710000e-43,5.610000e-08,2,observed
412,7162015_1,110,2,transit,1,0,66.495107,0.992844,963 walk_access 27023 premium_bus 80_GG80SB_74...,1.00,0,74.464458,4.580000e-33,4.590000e-33,9.962314e-01,2,observed
413,7163730_1,111,2,transit,1,0,18.500106,0.279186,310 walk_access 26624 local_bus MUN2O_19576 26...,1.00,0,23.006891,1.020000e-10,1.190000e-09,8.544593e-02,2,observed
414,7164607_2,112,2,transit,1,11,17.162059,0.045262,76 walk_access 20210 local_bus MUN44O_26259 33...,1.00,0,23.134000,8.970000e-11,5.280000e-09,1.699778e-02,2,observed
415,7198017_1,113,1,transit,1,2,113.835383,0.111058,321 walk_access 26818 local_bus MUN24O_22947 2...,1.00,0,123.468138,2.390000e-54,3.480000e-54,6.872255e-01,2,observed
416,7198017_1,114,2,transit,1,11,82.423203,0.001515,545 walk_access 27034 local_bus MUN36I_24728 2...,1.01,0,105.066300,2.350000e-46,4.230000e-46,5.550659e-01,2,observed
417,1383839_2,15,1,transit,2,1,50.340439,0.424088,482 walk_access 33197 local_bus MUN43I_25923 2...,2.00,0,51.457888,4.490000e-23,7.480000e-23,5.999600e-01,2,observed
418,1485392_1,20,1,transit,2,2,375.728941,0.196576,1198 walk_access 7312 local_bus 28_121_8465 73...,2.00,0,387.753502,3.990000e-169,8.620000e-168,4.627618e-02,2,observed
419,2525581_1,60,2,transit,2,0,81.359455,0.476990,711 walk_access 25197 local_bus MUN49O_27123 2...,2.00,0,84.532976,1.940000e-37,3.340000e-37,5.811738e-01,2,observed
420,2607105_1,64,1,transit,2,0,69.439313,0.700990,167 walk_access 22341 local_bus MUN94LI_28822 ...,2.00,0,71.011377,1.450000e-31,3.790000e-31,3.816754e-01,2,observed
421,7009053_1,81,1,transit,2,2,71.071121,0.253107,1191 walk_access 7688 local_bus 28_120NB_8668 ...,2.00,0,74.249682,5.670000e-33,2.660000e-32,2.132333e-01,2,observed

In [8]:
unique_fields = ['person_id','trip_list_id_num']

In [14]:
pd.DataFrame([df[col].astype('str') for col in unique_fields]).T

     person_id trip_list_id_num
0    1095531_3                1
1    1095531_3                1
2    1095531_3                1
3    1140514_1                2
4    1140514_1                2
5    1140514_1                2
6    1141305_1                3
7    1141305_1                3
8    1141305_1                3
9    1143233_3                4
10   1143233_3                4
11   1143233_3                4
12   1143233_3                4
13   1143233_3                4
14   1338147_1                5
15   1338147_1                5
16   1338147_1                5
17   1338147_1                5
18   1338147_1                5
19   1338147_1                6
20   1338147_1                6
21   1338147_1                6
22   1362557_3                7
23   1362557_3                7
24   1362557_3                7
25   1362557_3                8
26   1362557_3                8
27   1362557_3                8
28   1362557_4                9
29   1362557_4                9
..         ...              ...
842  1739050_1               39
843  1739050_1               39
844  1739050_1               39
845  1739050_1               39
846  1739050_1               39
847  2525581_1               60
848  2525581_1               60
849  2525581_1               60
850  2525581_1               60
851  2525581_1               60
852  2607105_1               64
853  2607105_1               64
854  2607105_1               64
855  7009053_1               81
856  7009053_1               81
857  7009053_1               81
858  7009053_1               81
859  7009053_1               81
860  7014476_5               83
861  7014476_5               83
862  7014476_5               83
863  7014476_5               83
864  7014476_5               83
865  7016330_1               86
866  7016330_1               86
867  7016330_1               86
868  7016330_1               86
869  7016330_1               86
870  7016330_1               86
871  7016330_1               86

[872 rows x 2 columns]