In [351]:
import pandas as pd
import numpy as np
# Load all the model results
chosenpaths_links = pd.read_csv(r'J:\Projects\FasTrips\tableau\path-set\chosenpaths_links.csv')
chosenpaths_paths = pd.read_csv(r'J:\Projects\FasTrips\tableau\path-set\chosenpaths_paths.csv')
pathset_links = pd.read_csv(r'J:\Projects\FasTrips\tableau\path-set\pathset_links.csv')
pathset_paths = pd.read_csv(r'J:\Projects\FasTrips\tableau\path-set\pathset_paths.csv')
routes= pd.read_csv(r'J:\Projects\FasTrips\obs\routes.txt')

In [380]:
# Model results
myline = pathset_paths['description'].iloc[0]

In [378]:
# Convert the description field into a list of routes only
# There is an oddly placed _, should fix in the output, but for now, eh
# setup is A_id mode B_id(?) routeid_[beginning of next record]
# Therefore, we need to split each one on the 5th record

# initial_array = myline.split(' ')

# # Split the 5th entry of this initial array 
# initial_array[len(initial_array)/2:1+len(initial_array)/2] = initial_array[len(initial_array)/2].split('_')

In [382]:
myline.split('_').split()

['152 walk',
 'access 23725 local',
 'bus MUN19I',
 '22085 23743 walk',
 'egress 544']

In [372]:
leninitial_array

['152',
 'walk_access',
 '23725',
 'local_bus',
 'MUN19I',
 '22085',
 '23743',
 'walk_egress',
 '544']

In [384]:
'MUN19I' in routes['']

False

In [391]:
pathset_links.groupby('route_id').count().index.values

array(['28_120NB', '28_120SB', '28_121', '28_122SB', '28_130NB',
       '28_130SB', '30_292N', '30_292NA', '30_292S', '30_292SA',
       '30_391NA', '30_391NB', '30_391NC', '30_391SA', '37_800EB',
       '37_800WB', '80_GG10NB', '80_GG10NBX', '80_GG10SB', '80_GG18NB',
       '80_GG18SB', '80_GG24NBA', '80_GG24NBB', '80_GG24SBB', '80_GG26NB',
       '80_GG27NB', '80_GG27SB', '80_GG2NB', '80_GG2SB', '80_GG38NB',
       '80_GG38SB', '80_GG44NB', '80_GG44SB', '80_GG4NB', '80_GG4SB',
       '80_GG54NB', '80_GG56NB', '80_GG58NB', '80_GG70NB', '80_GG72NB',
       '80_GG72SB', '80_GG72XNB', '80_GG74NB', '80_GG80SB', '80_GG8SB',
       'MUN10I', 'MUN10O', 'MUN12I', 'MUN12O', 'MUN14I', 'MUN14LI',
       'MUN14LO', 'MUN14O', 'MUN14SHORTI', 'MUN14SHORTO', 'MUN14XI',
       'MUN14XO', 'MUN16XI', 'MUN18I', 'MUN18O', 'MUN19I', 'MUN19O',
       'MUN1AXO', 'MUN1BXO', 'MUN1I', 'MUN1O', 'MUN1SHORTO', 'MUN21O',
       'MUN22I', 'MUN22O', 'MUN23I', 'MUN23O', 'MUN24I', 'MUN24O',
       'MUN27I', 'MUN27O', 'MUN28I', 'MUN28LO', 'MUN28O', 'MUN29I',
       'MUN29O', 'MUN2I', 'MUN2O', 'MUN30I', 'MUN30O', 'MUN30SHORTI',
       'MUN30SHORTO', 'MUN31AXI', 'MUN31I', 'MUN31O', 'MUN33I', 'MUN33O',
       'MUN36I', 'MUN37I', 'MUN37O', 'MUN38FTMI', 'MUN38FTMO', 'MUN38LI',
       'MUN38LO', 'MUN38PTLI', 'MUN38PTLO', 'MUN38_33RDI', 'MUN38_33RDO',
       'MUN39O', 'MUN3I', 'MUN3O', 'MUN41I', 'MUN43I', 'MUN43O', 'MUN44I',
       'MUN44O', 'MUN45I', 'MUN45O', 'MUN47I', 'MUN47O', 'MUN48I',
       'MUN48O', 'MUN49I', 'MUN49O', 'MUN52O', 'MUN54I', 'MUN5I', 'MUN5O',
       'MUN5SHORTI', 'MUN66O', 'MUN67O', 'MUN6I', 'MUN6O', 'MUN71I',
       'MUN71O', 'MUN82XI', 'MUN82XO', 'MUN8AXO', 'MUN8BXI', 'MUN8BXO',
       'MUN8XI', 'MUN8XO', 'MUN94LI', 'MUN9I', 'MUN9LI', 'MUN9O', 'MUNFI',
       'MUNFO', 'MUNJI', 'MUNJO', 'MUNKI', 'MUNKO', 'MUNLO', 'MUNMI',
       'MUNMO', 'MUNNI', 'MUNNO'], dtype=object)

In [345]:
[i in pathset_links.groupby('route_id').count().index.values for i in myline.split(' ')]

[False, False, False, False, False, False, False, False]

In [330]:
set(myline.split(' '))

{'152',
 '23725',
 '23743',
 '544',
 'MUN19I_22085',
 'local_bus',
 'walk_access',
 'walk_egress'}

In [355]:
'MUN19I' in pathset_links.groupby('route_id').count().index.values

True

In [352]:
routes[routes['agency_id'] == 'muni']

Empty DataFrame
Columns: [route_id, agency_id, route_short_name, route_long_name, route_type]
Index: []

In [325]:
'152' in routes.groupby('route_id').count().index.values

False

In [6]:
# Load the observed trip records

In [205]:
obs = pd.read_csv(r'R:\FastTrips\CHTS and OBS ft_output\OBS_ft_output_updated.csv')

In [206]:
# Pathset description example
# 152 walk_access 23715 local_bus MUN29I_22086 23752 walk_egress 544

In [207]:
obs.columns

Index([u'person_id', u'trip_list_id_num', u'linkmode', u'A_id_num', u'B_id_num', u'linknum', u'mode', u'route_id'], dtype='object')

In [208]:
obs.fillna('',inplace=True)
obs['person_id'] = obs['person_id'].apply(lambda x: x.split("_")[-1])
obs['concat'] = obs['A_id_num'].astype('str')+" "+obs['mode']+" "+obs['route_id']
obs['concat'] = obs['concat'].apply(lambda x: x.strip())
df1 = pd.DataFrame(obs.groupby(['person_id','trip_list_id_num'])['concat'].apply(lambda x: "%s" % ' '.join(x).strip()))
# df.to_csv('observed_chosenpaths_paths.csv')

In [209]:
# Group by person_id and trip_list_id_num to get chosen pathset
# Write

In [210]:
# Should we do the same thing from the chosen_trips?
ft = pd.read_csv(r'J:\Projects\FasTrips\obs\output\OBS to DynoDemand Conversion_stochastic_iter4_cap\ft_output_passenger_paths.csv')
ft['person_id'] = ft['person_id'].astype('str')
ft.fillna('',inplace=True)
ft['concat'] = ft['A_id_num'].astype('str')+" "+obs['mode'].astype('str')+" "+obs['route_id'].astype('str')
ft['concat'] = ft['concat'].astype('str').apply(lambda x: x.strip())
df2 = pd.DataFrame(ft.groupby(['person_id','trip_list_id_num'])['concat'].apply(lambda x: "%s" % ' '.join(x).strip()))

In [220]:
# df2['id'] = df2.index.get_level_values(0).values + "_" + df2.index.get_level_values(1).values.astype('str')
df2['id'] = df2.index.get_level_values(0).values

In [222]:
# df1['id'] = df1.index.get_level_values(0).values + "_" + df1.index.get_level_values(1).values.astype('str')
df1['id'] = df1.index.get_level_values(0).values

In [223]:
# Merge these things together
df = pd.merge(df1, df2, on='id')

In [224]:
df

,concat_x,id,concat_y
0,walk_access redacted commuter_rail Caltrain_Bu...,100,104133 walk_access 26067 light_rail MUNI 24439...
1,walk_access redacted local_bus MUNI transfer r...,1000,104805 walk_access 20432 express_bus AC Transi...
2,walk_access redacted local_bus Tri-Delta_392 r...,1000,104805 walk_access 20432 express_bus AC Transi...
3,walk_access redacted heavy_rail BART_32 43 red...,1000,104805 walk_access 20432 express_bus AC Transi...
4,walk_access redacted local_bus Sonoma County_6...,100004,105461 commuter_rail Caltrain_Tamien Palo Alto...
5,walk_access redacted local_bus Sonoma County_1...,100026,105114 local_bus SONOMA COUNTY TRANSIT 14031 t...
6,walk_access redacted local_bus Sonoma County_1...,100027,105900 walk_access 6978 walk_egress 14032 walk...
7,walk_access redacted local_bus Sonoma County_1...,100029,105579 KNR_access 6983 commuter_rail Caltrain_...
8,walk_access redacted local_bus Sonoma County_1...,100030,105900 walk_access 6978 commuter_rail Caltrain...
9,walk_access redacted local_bus Sonoma County_6...,100066,105234 walk_access 13630 local_bus MUNI 6886 t...
10,walk_access redacted local_bus Sonoma County_2...,100104,104855 walk_access 6878 commuter_rail Caltrain...
11,walk_access redacted local_bus Sonoma County_2...,100112,105369 walk_egress 6618 walk_access 6894 local...
12,walk_access redacted local_bus Sonoma County_2...,100115,105369 local_bus AC Transit_65 6618 walk_egres...
13,walk_access redacted local_bus Sonoma County_2...,100117,105740 walk_egress 6479 walk_access 5814 local...
14,walk_access redacted local_bus Sonoma County_2...,100120,105740 local_bus AC TRANSIT 6479 transfer 6619...
15,walk_access redacted local_bus SANTA ROSA CITY...,100125,105337 KNR_access 6886 commuter_rail Caltrain_...
16,walk_access redacted local_bus SANTA ROSA CITY...,100133,105337 walk_access 6886 commuter_rail Caltrain...
17,walk_access redacted local_bus Sonoma County_2...,100134,105907 transfer 6611 local_bus SAMTRANS 6637 w...
18,walk_access redacted local_bus Sonoma County_2...,100137,105369 transfer 6618 local_bus SAMTRANS 6352 w...
19,walk_access redacted local_bus SONOMA COUNTY T...,100138,105672 bike_access 6352 commuter_rail Caltrain...
20,walk_access redacted local_bus Sonoma County_2...,100146,105369 walk_access 6618 local_bus AC TRANSIT 6...
21,walk_access redacted local_bus Sonoma County_2...,100154,105719 walk_access 13708 commuter_rail Caltrai...
22,walk_access redacted local_bus Sonoma County_2...,100156,105114 walk_egress 9001 walk_access 14024 loca...
23,walk_access redacted local_bus SONOMA COUNTY T...,100157,105317 PNR_egress 6976 walk_access 6480 commut...
24,walk_access redacted local_bus SONOMA COUNTY T...,100158,105920 walk_access 6633 local_bus AC Transit_2...
25,walk_access redacted local_bus Sonoma County_4...,100251,105579 walk_access 6983 light_rail VTA 6615 tr...
26,walk_access redacted local_bus Sonoma County_4...,100252,105852 transfer 7030 local_bus AC Transit_217 ...
27,walk_access redacted local_bus Sonoma County_6...,100281,105461 local_bus AC Transit_217 6529 walk_egre...
28,walk_access redacted local_bus Sonoma County_6...,100287,105234 local_bus AC Transit_12 13630 walk_egre...
29,walk_access redacted local_bus SONOMA COUNTY T...,100291,105672 walk_access 6352 local_bus AC Transit_B...
...,...,...,...
13487,walk_access redacted local_bus Napa Vine_10 re...,971,105247 transfer 7126 commuter_rail Caltrain_Sa...
13488,walk_access redacted walk_egress,971,105247 transfer 7126 commuter_rail Caltrain_Sa...
13489,PNR_access redacted commuter_rail Caltrain_San...,974,105509 walk_access 7668 local_bus Napa Vine_2 ...
13490,walk_access redacted local_bus Napa Vine_10 re...,974,105509 walk_access 7668 local_bus Napa Vine_2 ...
13491,walk_access redacted local_bus Tri-Delta_393 r...,974,105509 walk_access 7668 local_bus Napa Vine_2 ...
13492,walk_access redacted commuter_rail Caltrain_Ha...,975,104754 PNR_access 27545 commuter_rail Caltrain...
13493,walk_access redacted local_bus Napa Vine_11 re...,975,104754 PNR_access 27545 commuter_rail Caltrain...
13494,walk_access redacted local_bus Tri-Delta_392 r...,975,104754 PNR_access 27545 commuter_rail Caltrain...
13495,walk_access redacted commuter_rail Caltrain_Sa...,978,104409 walk_access 27023 local_bus NAPA VINE 5...
13496,walk_access redacted commuter_rail Caltrain_Sa...,978,105940 local_bus Napa Vine_7 7168 walk_egress ...
13497,walk_access redacted local_bus Tri-Delta_394 r...,978,104409 walk_access 27023 local_bus NAPA VINE 5...
13498,walk_access redacted local_bus Tri-Delta_394 r...,978,105940 local_bus Napa Vine_7 7168 walk_egress ...
13499,walk_access redacted light_rail MUNI transfer ...,98,104025 bike_access 22511 commuter_rail Caltrai...
13500,walk_access redacted heavy_rail BART transfer ...,980,104753 commuter_rail Caltrain_San Jose Palo Al...
13501,walk_access redacted local_bus Napa Vine_2 red...,980,104753 commuter_rail Caltrain_San Jose Palo Al...
13502,walk_access redacted local_bus Tri-Delta_394 r...,980,104753 commuter_rail Caltrain_San Jose Palo Al...
13503,bike_access redacted commuter_rail Caltrain_Re...,984,105111 local_bus Napa Vine_3 7646 walk_egress ...
13504,walk_access redacted local_bus Napa Vine_2 red...,984,105111 local_bus Napa Vine_3 7646 walk_egress ...
13505,walk_access redacted local_bus Tri-Delta_392 r...,984,105111 local_bus Napa Vine_3 7646 walk_egress ...
13506,walk_access redacted local_bus PRIVATE SHUTTLE...,987,104065 commuter_rail Caltrain_Menlo Park Hills...
13507,walk_access redacted local_bus SOLTRANS transf...,987,104065 commuter_rail Caltrain_Menlo Park Hills...
13508,walk_access redacted local_bus TRI-DELTA trans...,987,104065 commuter_rail Caltrain_Menlo Park Hills...
13509,walk_access redacted commuter_rail Caltrain_Sa...,989,104353 walk_egress 21552 walk_access 21486 exp...
13510,walk_access redacted local_bus Napa Vine_11 re...,989,104353 walk_egress 21552 walk_access 21486 exp...
13511,walk_access redacted local_bus Tri-Delta_392 r...,989,104353 walk_egress 21552 walk_access 21486 exp...
13512,walk_access redacted commuter_rail Caltrain_Sa...,995,104864 local_bus Napa Vine_5 27550 walk_egress...
13513,KNR_access redacted local_bus NAPA VINE transf...,995,104864 local_bus Napa Vine_5 27550 walk_egress...
13514,bike_access redacted local_bus Tri-Delta_393 r...,995,104864 local_bus Napa Vine_5 27550 walk_egress...
13515,walk_access redacted commuter_rail Caltrain_Sa...,997,104333 KNR_access 24768 commuter_rail Caltrain...
13516,walk_access redacted local_bus Napa Vine_10 re...,997,104333 KNR_access 24768 commuter_rail Caltrain...

In [262]:
# chosenpaths_links['route_id'].replace('nan','', regex=True)

In [266]:
############### Create transit route list from the chosen pathset_links
# For the model
chosenpaths_links['route_id'] = chosenpaths_links['route_id'].str.replace('nan', repl="", n=-1, case=True, flags=0)
chosenpaths_links['route_id'] = chosenpaths_links['route_id'].astype('str')
df = pd.DataFrame(chosenpaths_links.groupby(['person_id','trip_list_id_num','iteration'])['route_id'].apply(lambda x: "%s" % ' '.join(x).strip()))

In [275]:
df.to_csv('test.csv')

In [294]:
# Get the common transit routes
list1 = filter(None,df['route_id'].iloc[6].split(" "))
list2 = ['MUN5I']
common = list(set(list1).intersection(list2))

# whole or partial match
# Difference in list length
abs(len(list2) - len(list1))

# for whole matches
# if difference is 0, list whole column as 1

# for partial match
# if difference is less than the length of the model column, but > 0, list as 1

1

In [295]:
common

['MUN5I']

In [13]:
def prep_df(data, record_type, unique_fields ,colname='record_type'):
	'''Load text data as df, create unique trip record ID, and tag as model/observed record'''
	df = pd.read_csv(data)
	df[colname] = record_type    # tag as model/observed record
	
	# Convert all specified unique_fields to string and concatenate as new unique_id field 
	df[unique_fields] = pd.DataFrame([df[col].astype('str') for col in unique_fields]).T
	df['unique_id'] = df[unique_fields].apply(lambda x: ''.join(x), axis=1)

	return df

In [16]:
model = prep_df(data=r'J:\Projects\FasTrips\tableau\path-set\chosenpaths_links.csv', record_type='model', unique_fields=['person_id','trip_list_id_num'])

In [21]:
obs

,person_id,trip_list_id_num,link_mode,A_id_num,B_id_num,linknum,mode,route_id
0,hh1_1,0,access,NaN,redacted,0,bike_access,NaN
1,hh1_1,0,transit,redacted,redacted,1,commuter_rail,San Francisco Palo Alto
2,hh1_1,0,egress,redacted,NaN,2,bike_egress,NaN
3,hh2_10,1,access,NaN,redacted,0,KNR_access,NaN
4,hh2_10,1,transit,redacted,redacted,1,commuter_rail,Millbrae Palo Alto
5,hh2_10,1,egress,redacted,NaN,2,walk_egress,NaN
6,hh3_100,2,access,NaN,redacted,0,walk_access,NaN
7,hh3_100,2,transit,redacted,redacted,1,commuter_rail,Burlingame California Ave
8,hh3_100,2,egress,redacted,NaN,2,walk_egress,NaN
9,hh4_1000,3,access,NaN,redacted,0,walk_access,NaN
10,hh4_1000,3,transit,redacted,NaN,1,local_bus,MUNI
11,hh4_1000,3,transfer,NaN,redacted,2,transfer,NaN
12,hh4_1000,3,transit,redacted,redacted,3,commuter_rail,San Francisco Burlingame
13,hh4_1000,3,egress,redacted,NaN,4,walk_egress,NaN
14,hh5_1001,4,access,NaN,redacted,0,walk_access,NaN
15,hh5_1001,4,transit,redacted,redacted,1,commuter_rail,San Jose San Francisco
16,hh5_1001,4,egress,redacted,NaN,2,KNR_egress,NaN
17,hh6_1002,5,access,NaN,redacted,0,walk_access,NaN
18,hh6_1002,5,transit,redacted,redacted,1,commuter_rail,Mountain�View Millbrae
19,hh6_1002,5,transfer,redacted,NaN,2,transfer,NaN
20,hh6_1002,5,transit,NaN,redacted,3,heavy_rail,BART
21,hh6_1002,5,egress,redacted,NaN,4,walk_egress,NaN
22,hh7_1003,6,access,NaN,redacted,0,walk_access,NaN
23,hh7_1003,6,transit,redacted,NaN,1,local_bus,PRIVATE SHUTTLE
24,hh7_1003,6,transfer,NaN,redacted,2,transfer,NaN
25,hh7_1003,6,transit,redacted,redacted,3,commuter_rail,Palo Alto San Jose
26,hh7_1003,6,egress,redacted,NaN,4,PNR_egress,NaN
27,hh8_1004,7,access,NaN,redacted,0,walk_access,NaN
28,hh8_1004,7,transit,redacted,NaN,1,local_bus,MUNI
29,hh8_1004,7,transfer,NaN,redacted,2,transfer,NaN
...,...,...,...,...,...,...,...,...
97171,hh26393_9253370632,26392,transit,redacted,redacted,1,commuter_rail,ACE
97172,hh26393_9253370632,26392,transfer,redacted,NaN,2,transfer,NaN
97173,hh26393_9253370632,26392,transit,NaN,redacted,3,local_bus,VTA
97174,hh26393_9253370632,26392,egress,redacted,NaN,4,walk_egress,NaN
97175,hh26394_9253515113,26393,access,NaN,redacted,0,KNR_access,NaN
97176,hh26394_9253515113,26393,transit,redacted,redacted,1,commuter_rail,ACE
97177,hh26394_9253515113,26393,egress,redacted,NaN,2,PNR_egress,NaN
97178,hh26395_9253663180,26394,access,NaN,redacted,0,PNR_access,NaN
97179,hh26395_9253663180,26394,transit,redacted,redacted,1,commuter_rail,ACE
97180,hh26395_9253663180,26394,transfer,redacted,NaN,2,transfer,NaN
97181,hh26395_9253663180,26394,transit,NaN,redacted,3,local_bus,PRIVATE SHUTTLE
97182,hh26395_9253663180,26394,egress,redacted,NaN,4,walk_egress,NaN
97183,hh26396_9255180029,26395,access,NaN,redacted,0,PNR_access,NaN
97184,hh26396_9255180029,26395,transit,redacted,redacted,1,commuter_rail,ACE
97185,hh26396_9255180029,26395,transfer,redacted,NaN,2,transfer,NaN
97186,hh26396_9255180029,26395,transit,NaN,redacted,3,local_bus,VTA
97187,hh26396_9255180029,26395,egress,redacted,NaN,4,walk_egress,NaN
97188,hh26397_9258580869,26396,access,NaN,redacted,0,KNR_access,NaN
97189,hh26397_9258580869,26396,transit,redacted,NaN,1,local_bus,VTA
97190,hh26397_9258580869,26396,transfer,NaN,redacted,2,transfer,NaN
97191,hh26397_9258580869,26396,transit,redacted,redacted,3,commuter_rail,ACE
97192,hh26397_9258580869,26396,egress,redacted,NaN,4,KNR_egress,NaN
97193,hh26398_9259891929,26397,access,NaN,redacted,0,PNR_access,NaN
97194,hh26398_9259891929,26397,transit,redacted,redacted,1,commuter_rail,ACE
97195,hh26398_9259891929,26397,transfer,redacted,NaN,2,transfer,NaN
97196,hh26398_9259891929,26397,transit,NaN,redacted,3,local_bus,VTA
97197,hh26398_9259891929,26397,egress,redacted,NaN,4,walk_egress,NaN
97198,hh26399_9494006534,26398,access,NaN,redacted,0,KNR_access,NaN
97199,hh26399_9494006534,26398,transit,redacted,redacted,1,commuter_rail,ACE
97200,hh26399_9494006534,26398,egress,redacted,NaN,2,PNR_egress,NaN

In [19]:
observed

NameError: name 'observed' is not defined